### ISSUE TITLE
Update quickstart info in README

### ISSUE THREAD

**Issue by accraze** [discogs/python-livingdocs#1]
After the last codeblock in the Quick Start section of the **README** we need to explain how about how/where the test steps and screenshots are stored. 

Here's a basic explanation:

After you have successfully ran your tests, each test step will create its own documentation (and corresponding screenshot if you are using Selenium WebDriver). These new files will be placed in`livingdocs/content/features`. Once you have generated these files, we can build our static Hugo site with the following commands:

```
$ cd livingdocs
$ hugo
```

You will now have a static living docs site in the `livingdocs/public` directory.

**Comment by Lakshya1605** [comment]
I would like to work on this.Should i just up date the Readme file with the given information or add more to it .Thank you

**Comment by accraze** [comment]
resolved by #2
