### ISSUE TITLE
Fix code commands in README

### ISSUE THREAD

**Issue by accraze** [discogs/python-livingdocs#4]
In the Quick Start section, we should fix this line:

>  we can build our static Hugo site with the following commands: $ cd livingdocs $ hugo

So it says:

>  we can build our static Hugo site with the following commands: 
> 
> ```
>  $ cd livingdocs 
>  $ hugo
> ```

**Comment by danielbayerlein** [comment]
@accraze Done 😉

**Comment by accraze** [comment]
resolved by #5
